version: 2
updates:
  - directory: /
    package-ecosystem: gomod
    schedule:
      interval: daily
  - directory: /terraform
    package-ecosystem: terraform
    schedule:
      interval: daily
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily